### ISSUE TITLE
Investigate performance issues

### ISSUE THREAD

**Issue by oskar** [oskar/raycing#36]
Raycing seems to be pretty CPU intensive..

![image](https://cloud.githubusercontent.com/assets/6519/11318687/c699e0c2-905c-11e5-8be8-4bbaf4ea2d5a.png)

**Comment by oskar** [comment]
Det räcker med att ladda startsidan och vänta lite så går CPU upp. Testade att stänga av stjärnorna på riktigt (inte bara göra de osynliga som knappen gör) genom att kommentera bort följande rader

    for(var i = 0; i < 100; i++){
      var start = new Paper.Point.random().multiply(outerBounds.bottomRight);
      animateStar(start);
    }

Då blir det mycket bättre :-) Funderar lite på den här rekursiva funktionen animateStar().. Det känns inte som att man någonsin avregistrerar callbacks från animation-objektet och eftersom man hela tiden lägger till nya stjärnor blir det nog rätt många efter ett tag? Kanske kan testa att skippa rekursionen och återanvända stjärnorna varje gång de försvinner utanför outerBounds?

**Comment by Korla** [comment]
Låter som en bra idé :+1:
