### ISSUE TITLE
Not possible to move end zone when editing map

### ISSUE THREAD

**Issue by oskar** [oskar/raycing#37]
1. Create new map
2. Place an end zone
3. Erase the end zone
4. Try to place another end zone some where else, not possible

**Comment by oskar** [comment]
The same is valid for start zone as well.

**Comment by Korla** [comment]
Known issue, there is code to detect the empty zone, but Paper doesn't remove the path completely. A limit should be used instead.

A workaround is to extend the zone to desired location, and erase the parts not needed, instead of removing it completely.

**Comment by Korla** [comment]
Changed empty check from path.isEmpty() to path.area < 50, in case the erasing missed a spot.
