### ISSUE TITLE
Set up github pages with live demo of game

### ISSUE THREAD

**Issue by oskar** [oskar/raycing#6]

**Comment by oskar** [comment]
@Korla is there a way to package the source code and dependencies with npm? I need all files needed to host a demo of the game.

**Comment by oskar** [comment]
Ah found it. The command I was looking for is `webpack`:-P

**Comment by oskar** [comment]
Project web page and live demo available here http://oskar.github.io/raycing/

**Comment by Korla** [comment]
Cool!
