### ISSUE TITLE
Should be straight lines between each point/dot on map

### ISSUE THREAD

**Issue by oskar** [oskar/raycing#7]

**Comment by Korla** [comment]
Works for angles non-divisible by 90 at the moment.

**Comment by oskar** [comment]
Heh, interesting bug. How come?

![image](https://cloud.githubusercontent.com/assets/6519/10329938/a15be890-6cc7-11e5-8534-5d631991a1de.png)

**Comment by Korla** [comment]
'Works for angles non-divisible by 90 at the moment.'

**Comment by oskar** [comment]
This seems fixed now
