### ISSUE TITLE
Introduce track concept

### ISSUE THREAD

**Issue by oskar** [oskar/raycing#9]
An area/surface which the cars cannot leave without getting disqualified.

* A track has a start line and a finish line
* A game starts with all players on the start line
* A game ends when any player crosses the finish line

**Comment by Korla** [comment]
Finish implemented with rectangular area that detects a car entering.

**Comment by oskar** [comment]
Awesome! Can we use a similar rectangle as a simple track? I.e. a rectangle between the start and finish area that you cannot leave / go outside of.

**Comment by Korla** [comment]
Absolutely, but I wasn't sure that a single rectangle was enough to represent the track properly. I was toying with the idea of multiple overlapping rectangles to add more features to the track.

**Comment by oskar** [comment]
I guess we will hit the limit with rectangles pretty soon but it might work as track for a while. I think the minimum requirement for a track for 0.1 is that it should have at least one curve. If that's doable with rectangle we can try it out.

**Comment by oskar** [comment]
As per the initial requirements, this enhancement seems fulfilled now, closing.
